---
# Jobs reference https://kubernetes.io/docs/concepts/jobs/run-to-completion-finite-workloads/
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-data-loader-with-timeout
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: mysql-data-loader
    spec:
      containers:
      - name: mysql-data-loader
        image: captainshar/php-dbconnect
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: password
          - name: MYSQL_HOST
            value: mysql.default.svc.cluster.local
        #update to execute my bash script instead
        # data loader bash script:
        #1. Wait for MySQL to be reachable
        #2. Check to see if data is already installed
        #3. Download data from internet
        #4. Load it up
        #5. Return success (exit code 0)
        #Error/time out perhaps
        #URL to download data is a parameter/env variable?
        command: ["/tmp/mysql-sakila-data-loader.sh"]
      restartPolicy: Never
