# create and claim a persistent volume for our pod
# this works because we enabled cloud-provider=aws
# so it can create a disk for itself

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
#    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# deploy the mysql container

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-dbconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-dbconnect
  template:
    metadata:
      labels:
        run: php-dbconnect
    spec:
      # deploying PHP from the specified Docker Hub image
      containers:
      - image: captainshar/php-dbconnect
        name: php-dbconnect
        #this was recommended for the mysql pod - same defaults for php pod?
        resources:
          requests:
            cpu: 1
            memory: 2Gi
        env:
          #replace with a proper secret handling
          #add another user?
          - name: MYSQL_ROOT_PASSWORD
            value: starbuck
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/
          name: web
      volumes:
      - name: web
        configMap:
        persistentVolumeClaim:
          claimName: web

---
# expose this on mysql.svc.default.cluster to the cluster

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: php-dbconnect