#php deployment from captainshar/php-dbconnect
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-dbconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-dbconnect
  template:
    metadata:
      labels:
        app: php-dbconnect
    spec:
      # deploying PHP from the specified Docker Hub image
      containers:
      - image: captainshar/php-dbconnect
        imagePullPolicy: Always
        name: php-dbconnect
        #this was recommended for the mysql pod - same defaults for php pod?
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        env:
          #replace with a proper secret handling
          #add another user?
          - name: MYSQL_ROOT_PASSWORD
            value: starbuck
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort: 80

---
# expose this on web.svc.default.cluster to the cluster

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: php-dbconnect
  type: LoadBalancer

---
#load balancer
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-04-10T23:59:08Z
  name: web
  namespace: default
  resourceVersion: "1608046"
  selfLink: /api/v1/namespaces/default/services/web
  uid: af858dd2-1e49-11e7-9bdf-0668dce5fad1
spec:
  clusterIP: 10.110.64.240
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: php-dbconnect
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}