#php deployment from captainshar/php-dbconnect
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-dbconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-dbconnect
  template:
    metadata:
      labels:
        app: php-dbconnect
    spec:
      # deploying PHP from the specified Docker Hub image
      containers:
      - image: captainshar/php-dbconnect
        imagePullPolicy: Always
        name: php-dbconnect
        #this was recommended for the mysql pod - same defaults for php pod?
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        env:
          #replace with a proper secret handling
          #add another user?
          - name: MYSQL_ROOT_PASSWORD
            value: starbuck
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort: 80

---
# load balancer

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: php-dbconnect
  type: LoadBalancer