apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  # `echo -n starbuck | base64`
  rootpw: c3RhcmJ1Y2s=
  # `echo -n phpuser | base64`
  user: cGhwdXNlcg==
  # `echo -n userpw | base64`
  password: dXNlcnB3
